language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
  global:
    secure: RozpHxszBR0tYycZmR3ekoQIMfRamGC0Jsp8fMLxE0CrLhfomKGs8L7Eb+c8doTTxQp89kL5+NyZ47YYgUM9JfUmzs8J7Kcth+l6W4uaHjVi+dirg/RqZfBW80SCDlDpdFNxEEQ36YnKzTAInhtONrAvtJZveMHM/sBPbdTvrPxaHkS/9TJcGeQFYptmEYB3248PCP+s5ggufU8xqY+BBkDie0Gl/yqVBRFWR5+x5asEVRmcmhehQ1tkxfNVQPL7eDVbvas6GMjq+o7gTCTcT+kenxGpaDBf9vndSfnzDqFOFAD2Gp8sfE2xRX508zyRC14I8NiJdtm4Ro5R3EFE7VnsCoGzd+ObrwJmh5gTrjg1CFbyEIayaHo9wMqNUQoRJkgMuta6JmZZRn4OnzGOfDnH0knFk4DgubNwaPSM/P8xesfF5402/rfOgti72gS5Km1TsDztCeOFuCFMeMIeu+SNb4KTrlxwqoTIdTe1iz7ogSZAMZIzUNigif3/8/+dYhxERgOS586Ee7V9PCOggTMOuZH0+hFhW8uZL8uYwOSWWA+wnukxj5tLDFGKpLJfr36SpLXwhCgUyspEKaP95qXopGl85AELD5EOWEhzKN+QGZC5K/VL9Y8jAxvqmD6oqaPGfwibSXV1785ihWpolRUOyxyoW+ssfoBLy5qIh+U=

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - $ANDROID_TARGET
  - extra-android-support
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
  # Deep clone so we can get an accurate commit count for version code
  - git fetch --unshallow
  # Unencrypt server account key for play publisher
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3476a8f5fa31_key
    -iv $encrypted_3476a8f5fa31_iv -in play-service-account-key.json.enc -out play-service-account-key.json
    -d; fi
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
  - echo yes | sdkmanager "tools"
  # Install the system image.
  - sdkmanager "system-images;$ANDROID_TARGET;default;$ANDROID_ABI"
  # Create and start emulator for the script. Meant to race the install task.
  - mv tools/lib/libOpenglRender.so tools/lib/libOpenglRender.so.xxx
  - echo no | avdmanager create avd --force -n test -k "system-images;$ANDROID_TARGET;default;$ANDROID_ABI"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script: ./gradlew check connectedCheck --stacktrace

deploy:
  provider: releases
  api_key:
    secure: WK/kKL09FEBTCpQg5CDqfZorSybOL+TYMzylqKSgLUilAxByDK6tD0ZHSnNnoZjyX7wC8xhtA9jU/dChUHT4SGPoqDabn1EvfMlGuGym1iIzi76S9yo41llx5Ddjc1uTBsE8PhVWoqC889EeMoVkykOCoYytqJThw61Z9AEq1AWNX2ue/28YLfr0trZWDTZJHOFv61lW6zB0cSOtTCIa7I+//1OLL/pdwvFObj01p879ehctsvdBqPg00iFP6voJBCyu8v8rKEEJWRNT1qU39lb5xC/AR3CWNPXSfiIi7Er7bLJ1OhNXwDSugivaA/iIsBwooRt28reUbrdTkqk15HyU5xB7XsQHEAF6CjscS9wl0urtvNfWbLWV9R9oRAdC+q4OKcGbJ/TUrY5yRmm4V1WmC2V9utCM4iPjG7bSImdq7M7M7/d9YNAOFlLrKjC84PrPFR8bsZM8bO8BWxClyG6w8qpgstG/OcalNuAXsCeYZPSxr9iKlC9aIShH6VNgBQjgrpJ7aRqGD4cNekqfUQJ/7sHuZQJ7pw6rjdAsvkof87BGAjypdhGs5nZ7EysCCD3X7nWVP3TdcE2OfU1MCVSm+nugc40Yccreof2JuR0jgZWVN5evI+rn4wZvgUCVQYs5DJ+VI4qjiXA/tCmT3bKB2LhvfjwpgldxVyv0glc=
  skip_cleanup: true
  file: "./app/build/outputs/apk/release/app-release.apk"
  on:
    branch: master
    tags: true
    repo: shalzz/college-academics
after_deploy: "./gradlew publishRelease --stacktrace"
