language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug check --no-daemon
  --stacktrace; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew build check --no-daemon
  --stacktrace; fi
sudo: false
deploy:
  provider: releases
  api_key:
    secure: zmOEqC6xjAeq1s00Vfvuva1vPw3PGZrrNTz/yJwP5Cs2wOgLvSRbe1hJHqYvjyKdoqm2yhNdTTm+xQCv9tFa8+dW+5h2xwhERYywt4UdMa4bMMcGX18jqCTWjz4x73pEfv+xl1y+7nyW7chqL0HE73CJczlnkuq2KEiiIIHAmS+PMdJ+0jm7Bg901KMCjKixccNmUtD5E7S2ZJqgJg99VwrWeYG3xitcvn0x+Y2C3MuHgKIoPYp4DAQC7Y7sIYukj1jN+rIhorY4MIAf4rnZruli+AXs9pAhPzyqtMnrNArM5IXp9q29CR32uIjNNYAGIQWLOfMyjnel0VqlesXRGzaC/+UeWJwN92rGgaS+GbkNzFpRC5bdYAjnEO2Lo/DVZoNCSgOjXHgbZegTp0ZF76XJv1ZBol1PFbKl9/Sf1XORfTkYuP6e86pEvNvMcgS11xVrhZNAk8aNLQ3ZKxzkBksINuBr03v9zXwwtFzBlklNw0YD75QzFhMyBCZgfKRmVfWjsqFyCkjdo7BWAKEm+8dn6Xtu2L9N0KXf8X9YL43UihYZ8SRiLT8sn9gxLsDiMCvM5jwnrlWUT8yXP0qw9yRssep6phP0iq2WmMHh+ZBVrxPGPu+bfdMccAGoEMFsfH8wLFrpl5vTLy0C7F4Q7RsXOWrVGTpAckPdDG9GhmY=
  file: "./app/build/outputs/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_deploy: "./gradlew publishRelease --no-daemon --stacktrace"
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3476a8f5fa31_key
  -iv $encrypted_3476a8f5fa31_iv -in play-service-account-key.json.enc -out play-service-account-key.json
  -d; fi
env:
  global:
    secure: RozpHxszBR0tYycZmR3ekoQIMfRamGC0Jsp8fMLxE0CrLhfomKGs8L7Eb+c8doTTxQp89kL5+NyZ47YYgUM9JfUmzs8J7Kcth+l6W4uaHjVi+dirg/RqZfBW80SCDlDpdFNxEEQ36YnKzTAInhtONrAvtJZveMHM/sBPbdTvrPxaHkS/9TJcGeQFYptmEYB3248PCP+s5ggufU8xqY+BBkDie0Gl/yqVBRFWR5+x5asEVRmcmhehQ1tkxfNVQPL7eDVbvas6GMjq+o7gTCTcT+kenxGpaDBf9vndSfnzDqFOFAD2Gp8sfE2xRX508zyRC14I8NiJdtm4Ro5R3EFE7VnsCoGzd+ObrwJmh5gTrjg1CFbyEIayaHo9wMqNUQoRJkgMuta6JmZZRn4OnzGOfDnH0knFk4DgubNwaPSM/P8xesfF5402/rfOgti72gS5Km1TsDztCeOFuCFMeMIeu+SNb4KTrlxwqoTIdTe1iz7ogSZAMZIzUNigif3/8/+dYhxERgOS586Ee7V9PCOggTMOuZH0+hFhW8uZL8uYwOSWWA+wnukxj5tLDFGKpLJfr36SpLXwhCgUyspEKaP95qXopGl85AELD5EOWEhzKN+QGZC5K/VL9Y8jAxvqmD6oqaPGfwibSXV1785ihWpolRUOyxyoW+ssfoBLy5qIh+U=
